config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope '(:locale)', locale: /en|es/ do
	  root to: 'searches#index'

	  resources :searches
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
	SEARCH_TYPE = {keyword: 0, category: 1, random: 3}

	# parámetro virtual
  attr_accessor :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	def index
		@categories = Chuck::Api.get_request 'categories'
		@categories << 'random'
		@search = Search.new
	end

	def create
		@search = Search.new search_params

		if !params[:search][:email].blank?
			set_session params[:search][:email]
		end

		@search.email = session[:email] unless session[:email].nil?

		if !params[:search][:category].blank?
			@results = Chuck::Api.get_request "random?category=#{params[:search][:category]}"
			@search[:results] = @results
			@search[:search_type] = params[:search][:category] == 'random' ? 'random' : 'category'
			@search[:keyword] = params[:search][:category]
		elsif !params[:search][:keyword].blank?
			puts Chuck::Api.get_request "search?query=#{params[:search][:keyword]}"
			@results = Chuck::Api.get_request "search?query=#{params[:search][:keyword]}"
			@search[:results] = @results
			@search[:search_type] = 'keyword'
			@search[:keyword] = params[:search][:keyword]
		end

    if @search.save

      ChuckMailer.send_search(session[:email], @results).deliver_now unless session[:email].nil?
      render json: { results: @results }
    end
	end

	private
		def search_params
      params.require(:search).permit(:keyword, :search_type, :email)
    end

    def set_session email
    	session[:email] = email
    end

    def remove_session
    	session[:email] = nil
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChuckFacts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/_form.html.erb
<%#= form_with(model: search, local: true) do |form| %>
<%= form_tag searches_path, method: :post, remote: true, class: 'search-chuck' do %>

	<div class="field">
		<%= t('.email') %><br/>
    <%= email_field_tag '[search][email]' %>
  </div>

  <div class="field">
  	<%= t('.keyword') %><br/>
    <%= text_field_tag '[search][keyword]' %>
  </div>

  <div class="field">
  	<%= t('.category') %><br/>
    <%= select_tag '[search][category]', options_for_select(categories), include_blank: t('.empty_cat') %>
  </div>

  <div class="actions">
  	<%= submit_tag 'Enviar' %>
  </div>

<% end %>

app/views/searches/index.html.erb
<h1><%= t('.welcome') %></h1>

<%= t('.results_send_to', email: session[:email]) unless session[:email].blank? %>

<%= render 'form', search: @search, categories: @categories %>

<div class="results"></div>